import type { ComponentType } from "react";
import type { LucideProps } from "lucide-react";
import {
  ShoppingCart,
  Utensils,
  Car,
  Briefcase,
  Heart,
  Home,
  Zap,
  Gift,
  Plane,
  Coffee,
  Music,
  Film,
  BookOpen,
  Smartphone,
  Wifi,
  Scissors,
  Baby,
  Dumbbell,
  Landmark,
  TrendingUp,
  Wallet,
  PiggyBank,
  Coins,
  Receipt,
  GraduationCap,
  Stethoscope,
  Tag,
  Banknote,
  CreditCard,
  Package,
  Bus,
  Fuel,
  Cable,
  Gamepad2,
  PartyPopper,
  Shirt as ShirtIcon,
  Gem,
  Sprout,
  Paintbrush,
  User,
  Users,
  Calendar,
  FileText,
  BarChart3,
  Lightbulb,
  Mail,
  FolderOpen,
} from "lucide-react";

export interface CategoryLucideIcon {
  name: string;
  label: string;
  component: ComponentType<LucideProps>;
}

export const CATEGORY_LUCIDE_ICONS: CategoryLucideIcon[] = [
  { name: "ShoppingCart", label: "Shopping", component: ShoppingCart },
  { name: "Utensils", label: "Food", component: Utensils },
  { name: "Car", label: "Transport", component: Car },
  { name: "Briefcase", label: "Work", component: Briefcase },
  { name: "Heart", label: "Health", component: Heart },
  { name: "Home", label: "Home", component: Home },
  { name: "Zap", label: "Utilities", component: Zap },
  { name: "Gift", label: "Gift", component: Gift },
  { name: "Plane", label: "Travel", component: Plane },
  { name: "Coffee", label: "Drinks", component: Coffee },
  { name: "Music", label: "Music", component: Music },
  { name: "Film", label: "Entertainment", component: Film },
  { name: "BookOpen", label: "Education", component: BookOpen },
  { name: "Smartphone", label: "Tech", component: Smartphone },
  { name: "Wifi", label: "Internet", component: Wifi },
  { name: "Scissors", label: "Services", component: Scissors },
  { name: "ShirtIcon", label: "Clothing", component: ShirtIcon },
  { name: "Baby", label: "Childcare", component: Baby },
  { name: "Dumbbell", label: "Fitness", component: Dumbbell },
  { name: "Landmark", label: "Banking", component: Landmark },
  { name: "TrendingUp", label: "Investment", component: TrendingUp },
  { name: "Wallet", label: "Wallet", component: Wallet },
  { name: "PiggyBank", label: "Savings", component: PiggyBank },
  { name: "Coins", label: "Money", component: Coins },
  { name: "Receipt", label: "Bills", component: Receipt },
  { name: "GraduationCap", label: "School", component: GraduationCap },
  { name: "Stethoscope", label: "Medical", component: Stethoscope },
  { name: "Tag", label: "Tag", component: Tag },
  { name: "Banknote", label: "Cash", component: Banknote },
  { name: "CreditCard", label: "Card", component: CreditCard },
  { name: "Package", label: "Delivery", component: Package },
  { name: "Bus", label: "Bus", component: Bus },
  { name: "Fuel", label: "Fuel", component: Fuel },
  { name: "Cable", label: "Cable", component: Cable },
  { name: "Gamepad2", label: "Gaming", component: Gamepad2 },
  { name: "PartyPopper", label: "Party", component: PartyPopper },
  { name: "Gem", label: "Luxury", component: Gem },
  { name: "Sprout", label: "Nature", component: Sprout },
  { name: "Paintbrush", label: "Art", component: Paintbrush },
  { name: "User", label: "Personal", component: User },
  { name: "Users", label: "Family", component: Users },
  { name: "Calendar", label: "Event", component: Calendar },
  { name: "FileText", label: "Document", component: FileText },
  { name: "BarChart3", label: "Charts", component: BarChart3 },
  { name: "Lightbulb", label: "Ideas", component: Lightbulb },
  { name: "Mail", label: "Mail", component: Mail },
  { name: "FolderOpen", label: "Other", component: FolderOpen },
];

const ICON_MAP = new Map(CATEGORY_LUCIDE_ICONS.map((i) => [i.name, i.component]));

export function getLucideIcon(name: string | null | undefined): ComponentType<LucideProps> | null {
  if(!name) return null;
  return ICON_MAP.get(name) ?? null;
}
